---
title: "Python-kurs"
format:
    revealjs:
        theme: default
        width: 1200
        height: 800
code-annotations: hover
---

# Introduksjon

## Hvorfor Python?
- Enkel syntaks
- Allsidig
  - Automatisering med scripts
  - Dataanalyse med notebooks
  - Programvare med pakker
- Limspråk
  - Gir tilgang til toppmoderne programvare

## Eksempel: automatisering
```{python}
import polars as pl
from great_tables import GT, style, loc

table = GT(pl.read_excel("data/sales.xlsx")).tab_options(
    table_body_vlines_style="solid",
    table_width="100%",
    table_font_size="16pt",
    column_labels_font_weight="bold",
)
table.show()
```

##
```{.python code-line-numbers="1|3|4-8|9"}
import polars as pl

sales_data = pl.read_excel("sales.xlsx")
sales_summary = sales_data.group_by('salesperson').agg(
    pl.col('amount').sum().alias('total_sales'),
    pl.col('amount').count().alias('num_sales'),
    pl.col('amount').mean().alias('avg_sales'),
)
sales_summary
```

. . .

```{python}
from great_tables import GT

sales_data = pl.read_excel("data/sales.xlsx")
sales_summary = sales_data.group_by('product').agg(
    pl.col('amount').sum().alias('total_sales'),
)
GT(sales_summary).tab_options(
    table_width="50%",
    table_font_size="16pt",
    column_labels_font_weight="bold",
).show()
```

## Eksempel: dataanalyse


# Python concepts

## Variables

```{.python}
navn = "mattias"
alder = 30
har_bil = False
hobbyer = ["historie", "filosofi", "programmering", "piano"]

mattias = {
  "navn": "mattias",
  "alder": 30,
  "har_bil": False,
  "hobbyer": ["historie", "filosofi", "programmering", "piano"]
}
```

. . .

**Annotations**
```{.python}
navn: str = "mattias"
alder: int = 30
har_bil: bool = False
hobbyer: list = ["historie", "filosofi", "programmering", "piano"]

mattias: dict = {"navn": "mattias", "alder": 30, "har_bil": False, "hobbyer": ["historie", "filosofi", "programmering", "piano"]}
```


## Operators: Addition
```{.python}
# Floats
a = 2
b = 3.0
c = a + b # 5.0

# Lists
frukt = ["eple", "banan"]
grønnsaker = ["gulrot", "potet"]
sunn_mat = frukt * grønnsaker # ["eple", "banan", "gulrot", "potet"]

# Strings
fornavn = "mattias"
etternavn = "matthiesen"
brukernavn = fornavn + etternavn # "mattiasmatthiesen"
```


## Operators: Multiplication

Man kan multiplisere mer enn bare *tall*

```{python}
#| echo: True
#| code-line-numbers: false
#| output-location: column-fragment
2 * 3
```

. . .

```{python}
#| echo: True
#| code-line-numbers: false
#| output-location: column-fragment
2 / 3
```

. . .

```{python}
#| echo: True
#| code-line-numbers: false
#| output-location: column-fragment
["eple", "banan"] * 2
```

. . .

```{python}
#| echo: True
#| code-line-numbers: false
#| output-location: column-fragment
"mattias" * 2
```


## Operators: Comparison
Man *sammenligner* med

<div style="background-color: rgb(240,240,240);">
<center>`<` &emsp; `<=` &emsp; `>` &emsp; `>=` &emsp; `==`</center>
</div>
<br>

. . .

```{python}
#| echo: True
#| code-line-numbers: false
#| output-location: column-fragment
2 < 3
```

. . .


```{python}
#| echo: True
#| code-line-numbers: false
#| output-location: column-fragment
"mattias" == "Mattias"
```

. . .

```{python}
#| echo: True
#| code-line-numbers: false
#| output-location: column-fragment
(2 < 3) == ("mattias" == "Mattias")
```


## Operators: Eksempel
```{python}
#| echo: True
#| code-echo: False
mattias = {"navn": "mattias", "alder": 30, "hobbyer": ["historie", "piano"]}
gunnar = {"navn": "gunnar", "alder": 31, "hobbyer": ["gitar"]}
```

. . .

<br>

```{python}
#| echo: True
#| code-echo: False
#| output-location: fragment
mattias["alder"] + gunnar["alder"]
```

<br>

```{python}
#| echo: True
#| code-echo: False
#| output-location: fragment
mattias["hobbyer"] + gunnar["hobbyer"]
```

<br>

```{python}
#| echo: True
#| code-echo: False
#| output-location: fragment
max([mattias["alder"], gunnar["alder"]]) # 31
```


## Control flow: Loops and comprehensions

```{python}
#| echo: True
#| code-echo: False
personer = [
  {"navn": "mattias", "alder": 30},
  {"navn": "gunnar", "alder": 31},
  {"navn": "trond", "alder": 31},
]
```

. . .

**Loop**
```{python}
#| echo: True
#| code-echo: False
total_alder = 0
for person in personer:
  total_alder = total_alder + person["alder"]
  # alternativ: total_alder += person["alder"]
snittalder = total_alder / len(personer)
snittalder
```

. . .

**Comprehension**
```{python}
#| echo: True
#| code-echo: False
alle_aldre = [person["alder"] for person in personer]
total_alder = sum(alle_aldre)
total_alder
```


## Control flow: Conditions
```{python}
#| echo: True
#| code-echo: False
personer = [
  {"navn": "mattias", "alder": 30},
  {"navn": "gunnar", "alder": 31},
  {"navn": "trond", "alder": 17},
]
```

. . .

**Loop**
```{python}
#| echo: True
#| code-echo: False
total_alder = 0
for person in personer:
  alder = person["alder"]
  if alder > 18:
    total_alder += person["alder"]
total_alder
```

. . .

**Comprehension**
```{python}
#| echo: True
#| code-echo: False
alle_aldre = [person["alder"] for person in personer if person["alder"] > 18]
snittalder = sum(alle_aldre) / len(alle_aldre)
snittalder
```


## Control flow: Oppgave
Finn det største tallet som er mindre enn 1593
```{python}
#| echo: True
tall = [1111, 912, 1430, 2391, 1594]
```

. . .

<br>

:::: {.columns}

::: {.column width="50%"}
Ved bruk av *comprehension*,
```{python}
#| echo: True
#| code-line-numbers: false
svar = max([n for n in tall if n < 1593])
svar
```
:::

::: {.column width="50%"}
Ved bruk av *loop*,
```{python}
#| echo: True
#| code-line-numbers: false
svar = 0
for n in tall:
  if n < 1593 and n >= svar:
    svar = n
svar
```
:::

::::

## Functions

Funksjoner gjør kode *gjenbrukbar* og *generaliserbar*.

```{python}
#| echo: True
#| code-line-numbers: false

def find_conditional_largest(numbers, threshold):
  return max([n for n in numbers if n < threshold])

svar = find_conditional_largest(tall, 1593)
svar
```

## Functions: Namespaces

Variabler har **kontekstuell gyldighet**. Et variabelnavn er gyldig innen et *namespace*.

<br>

:::: {.columns}

::: {.column width="33.33%"}
```{python}
#| echo: True
#| output-location: fragment
#| code-line-numbers: false
divisor = 2

def divide(number):
  return number / divisor

divide(10)
```
:::

::: {.column width="33.33%"}
```{python}
#| echo: True
#| output-location: fragment
#| code-line-numbers: false
divisor = 2

def divide(number):
  divisor = 5
  return number / divisor

divide(10)
```
:::

::: {.column width="33.33%"}
```{python}
#| echo: True
#| output-location: fragment
#| code-line-numbers: false
divisor = 2

def divide(number, divisor):
  return number / divisor

divide(10, 5)
```
:::

::::

<br>
**LEGB-regelen**: Local > enclosing > global > built-in

## Classes
- Brukes mest av *package*-forfattere, for å gjøre det lettere å *bruke* deres kode (e.g. `pandas.DataFrame`).
- Brukes for å *samle* relatert kode som skal brukes flere ganger i samme program.

. . .

## Classes: Define

```{python}
class Person:
    def __init__(self, name, age, hobbies):
        self.name = name
        self.age = age
        self.hobbies = hobbies

    def likes_books(self):
        if "books" in self.hobbies:
            return True
        return False
```

```{.python code-line-numbers="1|2|3-5|7-10"}
class Person: # <1>
    def __init__(self, name, age, hobbies): # <2>
        self.name = name
        self.age = age
        self.hobbies = hobbies

    def likes_books(self):
        if "books" in self.hobbies:
            return True
        return False
```

1. En `class`-definisjon er en *oppskrift* på hvordan man lager klasse-*instanser*.
2. En *special method* som spesifiserer hvordan en instans skal konstrueres.

## Classes: Create instances
```{python}
#| echo: True
persons = [
    Person(name="mattias", age=30, hobbies=["books", "football"]),
    Person(name="gunnar", age=31, hobbies=[]),
]
```

. . .

```{python}
#| echo: True
#| output-location: fragment
for person in persons:
    if person.likes_books():
        print(person.name + " likes books")
```

## Lese dokumentasjon

- [Python Package Index (PyPI)](https://pypi.org/): Hvor python-pakker publiseres
